//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class ReportSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReportSettings defaultInstance = ((ReportSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReportSettings())));
        
        public static ReportSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report")]
        public string ReportFileFolder {
            get {
                return ((string)(this["ReportFileFolder"]));
            }
            set {
                this["ReportFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateFormal {
            get {
                return ((bool)(this["GenerateFormal"]));
            }
            set {
                this["GenerateFormal"] = value;
            }
        }
    }
}
